name: Katana

on:
  schedule:
    - cron: "7,18,29,41,56 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Cache packages  
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          
    - name: Install
      run: yarn install
      
    - name: Build
      run: node index.js
      
    - name: Update Katana files
      uses: test-room-7/action-update-file@v1
      with:
          file-path: '*-usdc.json'
          commit-msg: "Update prices $GITHUB_RUN_NUMBER"
          github-token: ${{ secrets.GITHUB_TOKEN }}
