# This is a basic workflow to help you get started with Actions

name: CI-Test

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo 'Hello, world! $GITHUB_RUN_NUMBER'

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build $GITHUB_RUN_NUMBER",
          echo "test, and deploy your project".
